services:
  avahi:
    command: --version
    image: ${IMAGE}:latest
    build:
      args:
        VERSION: ${VERSION}
      tags:
        - ${IMAGE}:${VERSION}
        - ${IMAGE}:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
