---
.docker:
  image: docker:latest
  services:
    - name: moby/buildkit:latest
      alias: buildkitd
      command: ["--addr", "tcp://0.0.0.0:9000"]
  before_script:
    - docker buildx create --use --driver remote tcp://buildkitd:9000
    - echo $DOCKER_AUTH_CONFIG >~/.docker/config.json
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: on_success

stages:
  - check
  - build

check:
  extends: .docker
  stage: check
  script:
    - docker buildx bake

build:
  extends: .docker
  stage: build
  script:
    - cd ${COMPONENT} || exit 0
    - if [ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]; then OPTIONS=--push; fi
    - docker buildx bake $OPTIONS
  rules:
    - changes:
        - ${COMPONENT}/**/*
  parallel:
    matrix:
      - COMPONENT:
          - snapraid



