---
.docker:
  image: docker:26.1.1
  services:
    - name: moby/buildkit:v0.13.2
      alias: buildkitd
      command: ["--addr", "tcp://0.0.0.0:9000"]
  before_script:
    - docker buildx create --use --driver remote tcp://buildkitd:9000
    - echo $DOCKER_AUTH_CONFIG >~/.docker/config.json

stages:
  - lint
  - build

lint:
  extends: .docker
  stage: lint
  script:
    - docker buildx bake
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"

build:
  extends: .docker
  stage: build
  script:
    - cd ${COMPONENT} || exit 0
    - if [ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]; then OPTIONS=--push; fi
    - docker buildx bake $OPTIONS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ${COMPONENT}/**/*
  parallel:
    matrix:
      - COMPONENT:
          - snapraid
          - mergerfs
