services:
  mergerfs:
    image: ${IMAGE}:latest
    command: ["/media/data*", "/pool", "-o", "debug"]
    build:
      args:
        VERSION: ${VERSION}
      tags:
        - ${IMAGE}:${VERSION}
        - ${IMAGE}:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ./test:/media
      - ./pool:/pool:shared

  check:
    image: busybox:latest
    command: sh -c 'cat /pool/*'
    depends_on:
      - mergerfs
    volumes:
    - ./pool:/pool
