services:
  test:
    image: sprat/snapraid:latest
    command: list
    tmpfs:
      - /media/data1
      - /media/data2
      - /media/parity
    configs:
      - source: snapraid_config
        target: /etc/snapraid.conf
    build:
      args:
        VERSION: ${VERSION}
      tags:
        - sprat/snapraid:${VERSION}
        - sprat/snapraid:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7

configs:
  snapraid_config:
    content: |
      data data1 /media/data1
      data data2 /media/data2
      content /media/data1/snapraid.content
      content /media/data2/snapraid.content
      parity /media/parity/snapraid.parity
