name: CI

"on": push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            mergerfs:
              - 'mergerfs/**'
            snapraid:
              - 'snapraid/**'

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v6

  build:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ fromJSON(needs.changes.outputs.components)[0] != null }}
    strategy:
      matrix:
        component: ${{ fromJSON(needs.changes.outputs.components) }}
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/bake-action@v6
        with:
          workdir: ${{ matrix.component }}
          push: ${{ github.ref == 'refs/heads/master' }}

  all-good:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - validate
      - build
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
